SELECT * FROM VW_JOREASSIGN vj WHERE vj.JONO = 'R2531500';

SELECT * FROM JOMOBILEUSERS j WHERE EMAILADDRESS = 'RAIHAN.SATRIO@JOWEB.COM';

SELECT * FROM JOUSERPROVINCEMUNICIPALITY j WHERE EMAILADDRESS = 'RAIHAN.SATRIO@JOWEB.COM';

SELECT * FROM LOCATIONMASTER l WHERE LOCATIONCODE = '00004';

SELECT * FROM JOTRANHDR j WHERE ACCTNO = '331626' AND DIVISIONCODE = 'NLZNT';

SELECT * FROM VW_FULLACCTNOV2 vf WHERE ACCTNO = '1474702331626';

SELECT * FROM ARACCTSUBSCRIBER a WHERE ACCTNO = '331626' AND DIVISIONCODE = 'NLZNT';

SELECT * FROM artranhdr WHERE ACCTNO = '331626' AND DIVISIONCODE ='NLZNT';